<a href="https://colab.research.google.com/github/Ali-Asgar-Lakdawala/NLP/blob/main/text_generation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
def read_file(filepath):
    with open(filepath) as f:
        str_text=f.read()
    return str_text

In [2]:
path=("/content/drive/MyDrive/nlp udemy/UPDATED_NLP_COURSE/06-Deep-Learning/moby_dick_four_chapters.txt")

In [3]:
import spacy
nlp = spacy.load('en',disable=['parser', 'tagger','ner'])

nlp.max_length = 1198623

In [4]:
def separate_punc(doc_text):
    return [token.text.lower() for token in nlp(doc_text) if token.text not in '\n\n \n\n\n!"-#$%&()--.*+,-/:;<=>?@[\\]^_`{|}~\t\n ']

In [5]:
d=read_file(path)

In [6]:
tokens = separate_punc(d)

In [7]:
len(tokens)

11338

## Create Sequences of Tokens

In [8]:

train_len=3+1

text_seq=[]

for i in range (train_len,len(tokens)):

  seq = tokens[i-train_len:i]

  text_seq.append(seq)


In [9]:
' '.join(text_seq[0])

'call me ishmael some'

In [10]:
from keras.preprocessing.text import Tokenizer

In [11]:
tokenizer=Tokenizer()
tokenizer.fit_on_texts(text_seq)
sequences = tokenizer.texts_to_sequences(text_seq)

In [12]:
sequences[0]

[956, 14, 263, 49]

In [13]:
tokenizer.index_word

{1: 'the',
 2: 'a',
 3: 'and',
 4: 'of',
 5: 'i',
 6: 'to',
 7: 'in',
 8: 'it',
 9: 'that',
 10: 'he',
 11: 'his',
 12: 'was',
 13: 'but',
 14: 'me',
 15: 'with',
 16: 'as',
 17: 'at',
 18: 'this',
 19: 'you',
 20: 'is',
 21: 'all',
 22: 'for',
 23: 'my',
 24: 'on',
 25: 'be',
 26: "'s",
 27: 'not',
 28: 'from',
 29: 'there',
 30: 'one',
 31: 'up',
 32: 'what',
 33: 'him',
 34: 'so',
 35: 'bed',
 36: 'now',
 37: 'no',
 38: 'about',
 39: 'into',
 40: 'or',
 41: 'by',
 42: 'were',
 43: 'out',
 44: 'harpooneer',
 45: 'had',
 46: 'then',
 47: 'have',
 48: 'an',
 49: 'some',
 50: 'little',
 51: 'upon',
 52: 'like',
 53: 'old',
 54: 'if',
 55: 'they',
 56: 'would',
 57: 'do',
 58: 'over',
 59: 'landlord',
 60: 'thought',
 61: 'room',
 62: 'when',
 63: 'could',
 64: "n't",
 65: 'night',
 66: 'here',
 67: 'head',
 68: 'such',
 69: 'which',
 70: 'man',
 71: 'did',
 72: 'sea',
 73: 'time',
 74: 'other',
 75: 'very',
 76: 'go',
 77: 'these',
 78: 'more',
 79: 'though',
 80: 'first',
 81: 'sort',


In [14]:
# returns the count of each word 
tokenizer.word_counts

OrderedDict([('call', 5),
             ('me', 382),
             ('ishmael', 23),
             ('some', 120),
             ('years', 24),
             ('ago', 16),
             ('never', 72),
             ('mind', 28),
             ('how', 52),
             ('long', 60),
             ('precisely', 8),
             ('having', 24),
             ('little', 120),
             ('or', 148),
             ('no', 156),
             ('money', 20),
             ('in', 872),
             ('my', 276),
             ('purse', 12),
             ('and', 1488),
             ('nothing', 44),
             ('particular', 24),
             ('to', 1000),
             ('interest', 4),
             ('on', 264),
             ('shore', 4),
             ('i', 1100),
             ('thought', 104),
             ('would', 108),
             ('sail', 16),
             ('about', 156),
             ('a', 1599),
             ('see', 64),
             ('the', 2392),
             ('watery', 4),
             ('part', 36),


In [15]:
vocabulary_size = len(tokenizer.word_counts)
vocabulary_size

2717

In [16]:
import numpy as np

In [17]:
sequences=np.array(sequences)
sequences

array([[ 956,   14,  263,   49],
       [  14,  263,   49,  220],
       [ 263,   49,  220,  316],
       ...,
       [  11,  241,   52,    2],
       [ 241,   52,    2, 2717],
       [  52,    2, 2717,   26]])

# Creating an LSTM based model

In [18]:
import keras
from keras.models import Sequential
from keras.layers import Dense,LSTM,Embedding

In [19]:
def create_model (vocabulary_size,seq_length):
  model= Sequential()
  model.add(Embedding(vocabulary_size,4,input_length=seq_length))
  model.add(LSTM(150,return_sequences=True))
  model.add(LSTM(150))
  model.add(Dense(150, activation='relu'))

  model.add(Dense(vocabulary_size,activation='softmax'))

  model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
   
  model.summary()
  
  return model




In [20]:
from tensorflow.keras.utils import to_categorical

In [21]:
sequences

array([[ 956,   14,  263,   49],
       [  14,  263,   49,  220],
       [ 263,   49,  220,  316],
       ...,
       [  11,  241,   52,    2],
       [ 241,   52,    2, 2717],
       [  52,    2, 2717,   26]])

In [22]:
X=sequences[:,:-1]
X

array([[ 956,   14,  263],
       [  14,  263,   49],
       [ 263,   49,  220],
       ...,
       [  11,  241,   52],
       [ 241,   52,    2],
       [  52,    2, 2717]])

In [23]:
y=sequences[:,-1]
y

array([  49,  220,  316, ...,    2, 2717,   26])

In [24]:
y=to_categorical(y, num_classes=vocabulary_size+1)

In [25]:
seq_len=X.shape[1]
seq_len

3

In [26]:
# define model
model = create_model(vocabulary_size+1, seq_len)

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 3, 4)              10872     
_________________________________________________________________
lstm (LSTM)                  (None, 3, 150)            93000     
_________________________________________________________________
lstm_1 (LSTM)                (None, 150)               180600    
_________________________________________________________________
dense (Dense)                (None, 150)               22650     
_________________________________________________________________
dense_1 (Dense)              (None, 2718)              410418    
Total params: 717,540
Trainable params: 717,540
Non-trainable params: 0
_________________________________________________________________


In [27]:
# fit model
model.fit(X, y, batch_size=128, epochs=300,verbose=1)

Epoch 1/300
89/89 [==============================] - 6s 31ms/step - loss: 7.0292 - accuracy: 0.0522
Epoch 2/300
89/89 [==============================] - 3s 31ms/step - loss: 6.3831 - accuracy: 0.0528
Epoch 3/300
89/89 [==============================] - 3s 30ms/step - loss: 6.3308 - accuracy: 0.0528
Epoch 4/300
89/89 [==============================] - 3s 31ms/step - loss: 6.2969 - accuracy: 0.0528
Epoch 5/300
89/89 [==============================] - 3s 31ms/step - loss: 6.2698 - accuracy: 0.0528
Epoch 6/300
89/89 [==============================] - 3s 30ms/step - loss: 6.2464 - accuracy: 0.0528
Epoch 7/300
89/89 [==============================] - 3s 31ms/step - loss: 6.2302 - accuracy: 0.0528
Epoch 8/300
89/89 [==============================] - 3s 30ms/step - loss: 6.2087 - accuracy: 0.0528
Epoch 9/300
89/89 [==============================] - 3s 30ms/step - loss: 6.1813 - accuracy: 0.0528
Epoch 10/300
89/89 [==============================] - 3s 30ms/step - loss: 6.1647 - accuracy: 0.0528

In [28]:
from random import randint
from keras.preprocessing.sequence import pad_sequences

In [56]:
def generate_text(model, tokenizer, seq_len, seed_text, num_gen_words):
    '''
    INPUTS:
    model : model that was trained on text data
    tokenizer : tokenizer that was fit on text data
    seq_len : length of training sequence
    seed_text : raw string text to serve as the seed
    num_gen_words : number of words to be generated by model
    '''
    
    # Final Output
    output_text = []
    
    # Intial Seed Sequence
    input_text = seed_text

    output_text.append(input_text)
    
    # Create num_gen_words
    for i in range(num_gen_words):
        
        # Take the input text string and encode it to a sequence
        encoded_text = tokenizer.texts_to_sequences([input_text])[0]
        
        # Pad sequences to our trained rate (50 words in the video)
        pad_encoded = pad_sequences([encoded_text], maxlen=seq_len, truncating='pre')
        
        # Predict Class Probabilities for each word
        predict_x=model.predict(pad_encoded) 
        classes_x=np.argmax(predict_x,axis=1)
        
        # Grab word
        pred_word = tokenizer.index_word[classes_x[0]] 
        
        # Update the sequence of input text (shifting one over with the new word)
        input_text += ' ' + pred_word
        
        output_text.append(pred_word)
        
    # Make it look like a sentence.
    return ' '.join(output_text)

### Grab a random seed sequence

In [33]:
text_seq[0]

['call', 'me', 'ishmael', 'some']

In [34]:
import random
random.seed(101)
random_pick = random.randint(0,len(text_seq))

In [35]:
random_seed_text = text_seq[random_pick]

In [36]:
random_seed_text

['thought', 'i', 'to', 'myself']

In [37]:
seed_text = ' '.join(random_seed_text)

In [38]:
seed_text

'thought i to myself'

In [57]:
generate_text(model,tokenizer,seq_len,seed_text=seed_text,num_gen_words=50)

"thought i to myself the man 's a human being just as i thought he must be some abominable savage or other shipped aboard of a whaleman in the south seas and perhaps the sun there produced these extraordinary effects upon the skin now while all these ideas were passing through me like lightning"

### Exploring Generated Sequence

In [64]:
for i,word in enumerate(d.split()):
    if word == 'whaleman':
        print(' '.join(d.split()[i-20:i+20]))
        print('\n')

of this; but soon an inkling of the truth occurred to me. I remembered a story of a white man--a whaleman too--who, falling among the cannibals, had been tattooed by them. I concluded that this harpooneer, in the course of


young palms. It was now quite plain that he must be some abominable savage or other shipped aboard of a whaleman in the South Seas, and so landed in this Christian country. I quaked to think of it. A peddler


